# TODO: config file to directly launch runCBO
# Graphs are ready, but we still need stuff to launch the Monitor and all the other parts of CBO
# This is a draft version of what is needed

cost_type: 1
n_initial_samples: 100

defaults:
  - _self_
  - graph: complete


hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/${graph.graph.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}
    subdir: ${graph.graph.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /