cost_type: 1
save_file: ${graph.graph.name}_graph_variable_cost_${cost_type}.pdf
n_initial_samples: 100

defaults:
  - _self_
  - algorithm: pomis
  - graph: complete

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/${graph.graph.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}
    subdir: ${graph.graph.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /