# TODO: config file to directly launch runCBO

# An integer representing the type of cost per node, i.e.,
# fix_equal = 1, fix_different = 2, fix_different_variable = 3, fix_equal_variable = 4.
cost_type: 1

# An integer representing the initial number of observational samples.
n_initial_samples: 100

# An integer representing the size of the initial interventional dataset.
n_interventions: 10

# An integer representing the number of additional observations collected for every decision.
n_new_observations: 20

# An integer representing the number of CBO trials
n_trials: 40

# Whether to minimise the cost or maximise the reward
task: "min"

# Whether to use a causal prior, i.e., True or False
causal_prior: True

# The seed to use for reproducibility
seed: 0

defaults:
  - _self_
  - algorithm: mis
  - graph: complete

hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/${graph.graph.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}
    subdir: ${graph.graph.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /