# This is a simple helper to test the different graphs

variable_cost: False

defaults:
  - _self_
  - graph: complete

save_file: ${graph.name}_graph_variable_cost_${variable_cost}.pdf


hydra:
  run:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}/${graph.name}
  sweep:
    dir: ${oc.env:XP_PATH}/${hydra.job.name}
    subdir: ${graph.name}
  job:
    config:
      override_dirname:
        kv_sep: _
        item_sep: /