C:
  _target_: cbo.graphs.Node.Node
  name: "C"
  parents_name:
    - "B"
  children_name:
    - "D"
    - "E"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon, B: np.exp(-B) + epsilon"
  fixed_cost: "${set_cost_value: ${cost_type}, 2}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  is_reward_var: False
