A:
  _target_: cbo.graphs.Node.Node
  name: "A"
  parents_name:
    - "U1"
    - "F"
  children_name:
    - "E"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon, U1, F: F**2  + U1 + epsilon"
  # Fixed cost for type 2,3 is also 1
  fixed_cost: 1
  variable_cost: False
  is_reward_var: False
