D:
  _target_: cbo.graphs.Node.Node
  name: "D"
  parents_name:
    - "C"
  children_name:
    - "E"
    - "Y"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon, C: np.exp(-C) / 10. + epsilon"
  fixed_cost: "${set_cost_value: ${cost_type}, 5}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: -5
  max_intervention: 5