U2:
  _target_: cbo.graphs.Node.Node
  name: "U2"
  children_name:
    - "B"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon: epsilon"
  is_reward_var: False
