B:
  _target_: cbo.graphs.Node.Node
  name: "B"
  parents_name:
    - "U2"
  children_name:
    - "C"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon, U2: U2 + epsilon"
  fixed_cost: "${set_cost_value: ${cost_type}, 10}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: -5
  max_intervention: 4
  is_reward_var: False
