F:
  _target_: cbo.graphs.Node.Node
  name: "F"
  children_name:
    - "A"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon: epsilon"
  fixed_cost: "${set_cost_value: ${cost_type}, 3}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: -4
  max_intervention: 4
  is_reward_var: False
