A:
  _target_: cbo.graphs.Node.Node
  name: "A"
  parents_name:
    - "U1"
    - "F"
  children_name:
    - "E"
  equation:
    _target_: cbo.graphs.StructuralEquations.StringEquation
    string_equation: "lambda epsilon, U1, F: F**2  + U1 + epsilon"
  fixed_cost: "${set_cost_value: ${cost_type}, 1}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  is_reward_var: False
