Y:
  _target_: cbo.graphs.Node.Node
  name: "Y"
  parents_name:
    - L
    - N
    - P
    - O
    - C
    - CO
    - TE
  equation:
    _target_: cbo.graphs.StructuralEquations.SklearnEquation
    sklearn_model:
      _target_: sklearn.linear_model.LinearRegression
  is_reward_var: True
