P:
  _target_: cbo.graphs.Node.Node
  name: "P"
  parents_name:
    - S
    - T
    - D
    - TE
  children_name:
    - Y
  equation:
    _target_: cbo.graphs.StructuralEquations.SklearnEquation
    sklearn_model:
      _target_: sklearn.linear_model.LinearRegression
  is_reward_var: False
