T:
  _target_: cbo.graphs.Node.Node
  name: "T"
  parents_name:
    - S
  children_name:
    - P
    - O
    - CO
  equation:
    _target_: cbo.graphs.StructuralEquations.SklearnEquation
    sklearn_model:
      _target_: sklearn.linear_model.LinearRegression
  fixed_cost: "${set_cost_value: ${cost_type}, 5}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: 2450
  max_intervention: 2500
  is_reward_var: False
