C:
  _target_: cbo.graphs.Node.Node
  name: "C"
  parents_name:
    - N
    - L
    - TE
  children_name:
    - Y
  equation:
    _target_: SklearnEquation
    sklearn_model: sklearn.linear_model.LinearRegression
  fixed_cost: "${set_cost_value: ${cost_type}, 2}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: 0
  max_intervention: 1
  is_reward_var: False
