S:
  _target_: cbo.graphs.Node.Node
  name: "S"
  parents_name:
    - TE
  children_name:
    - T
    - D
    - P
    - O
    - CO
  equation:
    _target_: SklearnEquation
    sklearn_model: sklearn.linear_model.LinearRegression
  is_reward_var: False
