N:
  _target_: cbo.graphs.Node.Node
  name: "N"
  children_name:
    - C
    - Y
  equation:
    _target_: cbo.graphs.StructuralEquations.GaussianMixture
    n_components: 3
  fixed_cost: "${set_cost_value: ${cost_type}, 1}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: -2
  max_intervention: 5
  is_reward_var: False
