O:
  _target_: cbo.graphs.Node.Node
  name: "O"
  parents_name:
    - S
    - T
    - D
    - TE
  children_name:
    - Y
  equation:
    _target_: sklearn.linear_model.LinearRegression
  fixed_cost: "${set_cost_value: ${cost_type}, 10}"
  variable_cost: "${set_variable_cost: ${cost_type}}"
  min_intervention: 2
  max_intervention: 4
  is_reward_var: False
