name: "Complete"
_target_: cbo.graphs.Graph.Graph
obs_path: ${oc.env:DATA_PATH}/complete_graph/observations.pkl
intervention_path: ${oc.env:DATA_PATH}/complete_graph/interventional_data.npy
initial_num_obs_samples: 100

defaults:
   - node@nodes:
        - complete_u1
        - complete_u2
        - complete_f
        - complete_a
        - complete_b
        - complete_c
        - complete_d
        - complete_e
        - complete_y
   - _self_
