defaults:
   - _self_

name: "Complete"
_target_: cbo.graphs.Graph.Graph
nodes:
   - graph_nodes/complete/u1
   - graph_nodes/complete/u2
   - graph_nodes/complete/f
   - graph_nodes/complete/a
   - graph_nodes/complete/b
   - graph_nodes/complete/c
   - graph_nodes/complete/d
   - graph_nodes/complete/e
   - graph_nodes/complete/y
obs_path: ${oc.env:DATA_PATH}/complete_graph/observations.pkl
intervention_path: ${oc.env:DATA_PATH}/complete_graph/interventional_data.npy
initial_num_obs_samples: 100