graph:
     _target_: cbo.graphs.CausalGraph.CausalGraph
     obs_path: ${oc.env:DATA_PATH}/complete_graph/observations.pkl
     interventions_path: ${oc.env:DATA_PATH}/complete_graph/interventional_data.npy
     n_initial_samples: ${n_initial_samples}
     name: "Complete"
     nodes: "${get_values: ${graph.nodes_dict}}"
     exploration_set_fn: algorithm/mis

defaults:
   - node@nodes_dict:
        - complete_u1
        - complete_u2
        - complete_f
        - complete_a
        - complete_b
        - complete_c
        - complete_d
        - complete_e
        - complete_y
   - _self_
