name: "Complete"
_target_: cbo.graphs.CausalGraph.CausalGraph
obs_path: ${oc.env:DATA_PATH}/complete_graph/observations.pkl
interventions_path: ${oc.env:DATA_PATH}/complete_graph/interventional_data.npy
n_initial_samples: 100  # TODO this is duplicated over all graphs may be better to put that in the CBO config

defaults:
   - node@nodes:
        - complete_u1
        - complete_u2
        - complete_f
        - complete_a
        - complete_b
        - complete_c
        - complete_d
        - complete_e
        - complete_y
   - _self_
