graph:
    _target_: cbo.graphs.CausalGraph.CausalGraph
    name: "Coral"
    obs_path: ${oc.env:DATA_PATH}/coral_graph/observations.pkl
    true_obs_path: ${oc.env:DATA_PATH}/coral_graph/true_observations.pkl
    interventions_path: ${oc.env:DATA_PATH}/coral_graph/interventional_data.npy
    n_initial_samples: ${n_initial_samples}
    nodes: "${get_values: ${graph.nodes_dict}}"

defaults:
   - node@nodes_dict:
       - coral_te
       - coral_c
       - coral_l
       - coral_s
       - coral_o
       - coral_p
       - coral_d
       - coral_t
       - coral_co
       - coral_n
       - coral_y
   - _self_