_target_: cbo.graphs.Graph.Graph
name: "Coral"
obs_path: ${oc.env:DATA_PATH}/simplified_coral_graph/observations.pkl
intervention_path: ${oc.env:DATA_PATH}/simplified_coral_graph/interventional_data.npy
initial_num_obs_samples: 100

defaults:
  - node@nodes:
      - coral_te
      - simplified_coral_c
      - coral_l
      - coral_s
      - simplified_coral_o
      - coral_p
      - simplified_coral_d
      - simplified_coral_t
      - coral_co
      - coral_n
      - coral_y
  - _self_