graph:
    _target_: cbo.graphs.CausalGraph.CausalGraph
    name: "Coral"
    obs_path: ${oc.env:DATA_PATH}/simplified_coral_graph/observations.pkl
    interventions_path: ${oc.env:DATA_PATH}/simplified_coral_graph/interventional_data.npy
    n_initial_samples: ${n_initial_samples}
    nodes: "${get_values: ${graph.nodes_dict}}"
    exploration_set: ${algorithm}

defaults:
  - node@nodes_dict:
      - coral_te
      - simplified_coral_c
      - coral_l
      - coral_s
      - simplified_coral_o
      - coral_p
      - simplified_coral_d
      - simplified_coral_t
      - coral_co
      - coral_n
      - coral_y
  - _self_