_target_: src.graphs.Node.Node
  name: "O"
  parent_name:
    - S
    - T
    - D
    - TE
  children_name:
    - Y
    equation:
      _target_: sklearn.linear_model.LinearRegression
    # Fixed cost for type 2,3 is 10
    fixed_cost: 1
    variable_cost: False
    min_internvention: 2
    max_intervention: 4