_target_: src.graphs.Node.Node
       name: "Y"
       parent_name:
         - L
         - N
         - P
         - O
         - C
         - CO
         - TE
       equation:
         _target_: sklearn.linear_model.LinearRegression