_target_: cbo.graphs.Node.Node
  name: "D"
  parent_name:
    - S
  children_name:
    - P
    - O
    - CO
    equation:
      _target_: sklearn.linear_model.LinearRegression
    # Fixed cost for type 2,3 is 20
    fixed_cost: 1
    variable_cost: False
    min_intervention: 2000
    max_invervention: 2080