_target_: src.graphs.Node.Node
       name: "C"
       parent_name:
         - "B"
       children_name:
         - "D"
         - "E"
       equation:
         _target_: src.graphs.StructuralEquations.StringEquation
         string_equation: "lambda epsilon, B: np.exp(-B) + epsilon"
       # Fixed cost for type 2,3 is 2
       fixed_cost: 1
       variable_cost: False