_target_: src.graphs.Node.Node
       name: "F"
       children_name:
         - "A"
       equation:
         _target_: src.graphs.StructuralEquations.StringEquation
         string_equation: "lambda epsilon: epsilon"
       # fixed_cost for type cost 2,3 is 3
       fixed_cost: 1
       variable_cost: False
       min_intervention: -4
       max_intervention: 4