 _target_: src.graphs.Node.Node
     name: "U1"
     children_name:
       - "A"
     equation:
        _target_: src.graphs.StructuralEquations.StringEquation
        string_equation: "lambda epsilon: epsilon"